version: "3.8"

services:
    user_service:
        build: ./user_service
        ports:
            - "3001:3001"
        env_file:
            - ./user_service/.env
        depends_on:
            - user_service_db
            - redis

    ticket_service:
        build: ./ticket_service
        ports:
            - "3002:3002"
        env_file:
            - ./ticket_service/.env
        depends_on:
            - ticket_service_db
            - redis

    order_service:
        build: ./order_service
        ports:
            - "3003:3003"
        env_file:
            - ./order_service/.env
        depends_on:
            - order_service_db
            - redis

    redisapi_service:
        build: ./redisAPI_service
        ports:
            - "3004:3004"
        env_file:
            - ./redisAPI_service/.env
        depends_on:
            - redis

    ticketwave_frontend:
        build: ./ticketwave_frontend
        ports:
            - "8080:80"
        depends_on:
            - user_service
            - ticket_service
            - order_service

    user_service_db:
        image: mysql:8.0
        container_name: user_service_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: user_service_db
        ports:
            - "3307:3306"
        volumes:
            - user_service_data:/var/lib/mysql

    ticket_service_db:
        image: mysql:8.0
        container_name: ticket_service_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: ticket_service_db
        ports:
            - "3308:3306"
        volumes:
            - ticket_service_data:/var/lib/mysql

    order_service_db:
        image: mysql:8.0
        container_name: order_service_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: order_service_db
        ports:
            - "3309:3306"
        volumes:
            - order_service_data:/var/lib/mysql

    redis:
        image: redis:7.2
        command: redis-server --requirepass ${REDIS_PASSWORD}
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "6379:6379"

volumes:
    user_service_data:
    ticket_service_data:
    order_service_data:
