services:
    frontend:
        build: ./ticketwave_frontend
        ports:
            - "8080:80"
        depends_on:
            - user_service
            - ticket_service
            - order_service
        networks:
            - default
    user_service:
        build: ./user_service
        ports:
            - "3001:3001"
        depends_on:
            - user_service_db
            - redis
        environment:
            - REDIS_HOST=redis
        env_file:
            - ./user_service/.env

    ticket_service:
        build: ./ticket_service
        ports:
            - "3002:3002"
        depends_on:
            - ticket_service_db
            - redis
        environment:
            - REDIS_HOST=redis
        env_file:
            - ./ticket_service/.env

    order_service:
        build: ./order_service
        ports:
            - "3003:3003"
        depends_on:
            - order_service_db
            - redis
        environment:
            - REDIS_HOST=redis
        env_file:
            - ./order_service/.env

    user_service_db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: user_service_db
        ports:
            - "3307:3306" # host:container
        volumes:
            - user_service_db_data:/var/lib/mysql

    ticket_service_db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: ticket_service_db
        ports:
            - "3308:3306" # host:container
        volumes:
            - ticket_service_db_data:/var/lib/mysql

    order_service_db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: order_service_db
        ports:
            - "3309:3306" # host:container
        volumes:
            - order_service_db_data:/var/lib/mysql

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

    redis_api_service:
        build: ./redisApi_service
        ports:
            - "3004:3004"
        depends_on:
            - redis
        environment:
            - PORT=3004
            - REDIS_HOST=redis
            - REDIS_PORT=6379

volumes:
    user_service_db_data:
    ticket_service_db_data:
    order_service_db_data:
    redis_data:
