apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ticketwave-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    ingressClassName: nginx
    rules:
        - http:
              paths:
                  - path: /api/users(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: user-service
                            port:
                                number: 3001
                  - path: /api/tickets(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: ticket-service
                            port:
                                number: 3002
                  - path: /api/orders(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: order-service
                            port:
                                number: 3003
                  - path: /api/events(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: redisapi-service
                            port:
                                number: 3004
