apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: order-service
    template:
        metadata:
            labels:
                app: order-service
        spec:
            containers:
                - name: order-service
                  image: your-dockerhub-username/order_service:latest
                  ports:
                      - containerPort: 3003
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "250m"
