apiVersion: apps/v1
kind: Deployment
metadata:
    name: ticket-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ticket-service
    template:
        metadata:
            labels:
                app: ticket-service
        spec:
            containers:
                - name: ticket-service
                  image: your-dockerhub-username/ticket_service:latest
                  ports:
                      - containerPort: 3002
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "250m"
