name: Deploy Ticket Service

on:
    push:
        branches: [main]
        paths:
            - "ticket_service/**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: andres050588/ticket_service
            SERVICE_NAME: ticket-service

        steps:
            - uses: actions/checkout@v3

            - uses: docker/setup-buildx-action@v2

            - uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker image
              run: |
                  docker buildx build \
                    --platform linux/amd64 \
                    -t $IMAGE_NAME:latest \
                    -t $IMAGE_NAME:${{ github.sha }} \
                    --push ./ticket_service

            - name: Setup Kubeconfig
              run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

            - name: Update deployment
              run: kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$IMAGE_NAME:${{ github.sha }}
