name: Deploy User Service

on:
    push:
        branches: [main]
        paths:
            - "user_service/**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: andres050588/user_service
            SERVICE_NAME: user-service

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: 🛠️ Build and Push Docker Image
              run: |
                  docker buildx build \
                    --platform linux/amd64 \
                    -t $IMAGE_NAME:latest \
                    -t $IMAGE_NAME:${{ github.sha }} \
                    --push ./user_service

            - name: Auth + Get GKE Credentials
              uses: google-github-actions/get-gke-credentials@v1
              with:
                  credentials: ${{ secrets.GCP_SA_KEY }}
                  cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
                  location: ${{ secrets.GKE_REGION }}
                  project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Update Kubernetes Deployment
              run: |
                  kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$IMAGE_NAME:${{ github.sha }}
