name: Deploy Order Service

on:
    push:
        branches: [main]
        paths:
            - "order_service/**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: andres050588/order_service
            SERVICE_NAME: order-service

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: 🛠️ Build and Push Docker Image
              run: |
                  docker buildx build \
                    --platform linux/amd64 \
                    -t $IMAGE_NAME:latest \
                    -t $IMAGE_NAME:${{ github.sha }} \
                    --push ./order_service

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Setup Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Install GKE Auth Plugin
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

            - name: Get GKE credentials
              run: |
                  gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
                    --region ${{ secrets.GKE_REGION }}

            - name: Update Kubernetes Deployment
              run: |
                  kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$IMAGE_NAME:${{ github.sha }}
